plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - ./golang/logical_thinking.md
  - ./golang/go_struct.md
  - ./golang/options_pattern.md
  - ./golang/chanels.md
  - ./golang/why_go_jp.md
  - ./golang/benchmark.md
  - ./golang/golang_effective_notes.md
  - ./golang/clean_architecture.md
  - ./healthline/sleep-pattern.md
  - ./aws/cognito.md
  - ./aws/csap.md
theme: jekyll-theme-cayman
